# automatically generated by the FlatBuffers compiler, do not modify

# namespace: GroceryOrderProto

import flatbuffers
from flatbuffers.compat import import_numpy
np = import_numpy()

class Grocery(object):
    __slots__ = ['_tab']

    @classmethod
    def GetRootAs(cls, buf, offset=0):
        n = flatbuffers.encode.Get(flatbuffers.packer.uoffset, buf, offset)
        x = Grocery()
        x.Init(buf, n + offset)
        return x

    @classmethod
    def GetRootAsGrocery(cls, buf, offset=0):
        """This method is deprecated. Please switch to GetRootAs."""
        return cls.GetRootAs(buf, offset)
    # Grocery
    def Init(self, buf, pos):
        self._tab = flatbuffers.table.Table(buf, pos)

    # Grocery
    def Veggies(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(4))
        if o != 0:
            x = o + self._tab.Pos
            from Proto.GroceryOrderProto.Veggies import Veggies
            obj = Veggies()
            obj.Init(self._tab.Bytes, x)
            return obj
        return None

    # Grocery
    def Drinks(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(6))
        if o != 0:
            x = o + self._tab.Pos
            from Proto.GroceryOrderProto.Container import Container
            obj = Container()
            obj.Init(self._tab.Bytes, x)
            return obj
        return None

    # Grocery
    def Milk(self, j):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(8))
        if o != 0:
            x = self._tab.Vector(o)
            x += flatbuffers.number_types.UOffsetTFlags.py_type(j) * 8
            from Proto.GroceryOrderProto.Milk import Milk
            obj = Milk()
            obj.Init(self._tab.Bytes, x)
            return obj
        return None

    # Grocery
    def MilkLength(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(8))
        if o != 0:
            return self._tab.VectorLen(o)
        return 0

    # Grocery
    def MilkIsNone(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(8))
        return o == 0

    # Grocery
    def Bread(self, j):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(10))
        if o != 0:
            x = self._tab.Vector(o)
            x += flatbuffers.number_types.UOffsetTFlags.py_type(j) * 8
            from Proto.GroceryOrderProto.Bread import Bread
            obj = Bread()
            obj.Init(self._tab.Bytes, x)
            return obj
        return None

    # Grocery
    def BreadLength(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(10))
        if o != 0:
            return self._tab.VectorLen(o)
        return 0

    # Grocery
    def BreadIsNone(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(10))
        return o == 0

    # Grocery
    def Meat(self, j):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(12))
        if o != 0:
            x = self._tab.Vector(o)
            x += flatbuffers.number_types.UOffsetTFlags.py_type(j) * 8
            from Proto.GroceryOrderProto.Meat import Meat
            obj = Meat()
            obj.Init(self._tab.Bytes, x)
            return obj
        return None

    # Grocery
    def MeatLength(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(12))
        if o != 0:
            return self._tab.VectorLen(o)
        return 0

    # Grocery
    def MeatIsNone(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(12))
        return o == 0

def GroceryStart(builder): builder.StartObject(5)
def Start(builder):
    return GroceryStart(builder)
def GroceryAddVeggies(builder, veggies): builder.PrependStructSlot(0, flatbuffers.number_types.UOffsetTFlags.py_type(veggies), 0)
def AddVeggies(builder, veggies):
    return GroceryAddVeggies(builder, veggies)
def GroceryAddDrinks(builder, drinks): builder.PrependStructSlot(1, flatbuffers.number_types.UOffsetTFlags.py_type(drinks), 0)
def AddDrinks(builder, drinks):
    return GroceryAddDrinks(builder, drinks)
def GroceryAddMilk(builder, milk): builder.PrependUOffsetTRelativeSlot(2, flatbuffers.number_types.UOffsetTFlags.py_type(milk), 0)
def AddMilk(builder, milk):
    return GroceryAddMilk(builder, milk)
def GroceryStartMilkVector(builder, numElems): return builder.StartVector(8, numElems, 4)
def StartMilkVector(builder, numElems):
    return GroceryStartMilkVector(builder, numElems)
def GroceryAddBread(builder, bread): builder.PrependUOffsetTRelativeSlot(3, flatbuffers.number_types.UOffsetTFlags.py_type(bread), 0)
def AddBread(builder, bread):
    return GroceryAddBread(builder, bread)
def GroceryStartBreadVector(builder, numElems): return builder.StartVector(8, numElems, 4)
def StartBreadVector(builder, numElems):
    return GroceryStartBreadVector(builder, numElems)
def GroceryAddMeat(builder, meat): builder.PrependUOffsetTRelativeSlot(4, flatbuffers.number_types.UOffsetTFlags.py_type(meat), 0)
def AddMeat(builder, meat):
    return GroceryAddMeat(builder, meat)
def GroceryStartMeatVector(builder, numElems): return builder.StartVector(8, numElems, 4)
def StartMeatVector(builder, numElems):
    return GroceryStartMeatVector(builder, numElems)
def GroceryEnd(builder): return builder.EndObject()
def End(builder):
    return GroceryEnd(builder)