# automatically generated by the FlatBuffers compiler, do not modify

# namespace: GroceryOrderProto

import flatbuffers
from flatbuffers.compat import import_numpy
np = import_numpy()

class Container(object):
    __slots__ = ['_tab']

    @classmethod
    def SizeOf(cls):
        return 24

    # Container
    def Init(self, buf, pos):
        self._tab = flatbuffers.table.Table(buf, pos)

    # Container
    def Cans(self, obj):
        obj.Init(self._tab.Bytes, self._tab.Pos + 0)
        return obj

    # Container
    def Bottles(self, obj):
        obj.Init(self._tab.Bytes, self._tab.Pos + 12)
        return obj


def CreateContainer(builder, cans_coke, cans_beer, cans_soda, bottles_sprite, bottles_gingerale, bottles_sevenup):
    builder.Prep(4, 24)
    builder.Prep(4, 12)
    builder.PrependUint32(bottles_sevenup)
    builder.PrependUint32(bottles_gingerale)
    builder.PrependUint32(bottles_sprite)
    builder.Prep(4, 12)
    builder.PrependUint32(cans_soda)
    builder.PrependUint32(cans_beer)
    builder.PrependUint32(cans_coke)
    return builder.Offset()
