# automatically generated by the FlatBuffers compiler, do not modify

# namespace: GroceryOrderProto

class MilkType(object):
    ONE_PCT = 0
    TWO_PCT = 1
    FAT_FREE = 2
    WHOLE = 3
    CASHEW = 4
    OAT = 5
