# automatically generated by the FlatBuffers compiler, do not modify

# namespace: CustomAppProto

import flatbuffers
from flatbuffers.compat import import_numpy
np = import_numpy()

class HealthStatusMessage(object):
    __slots__ = ['_tab']

    @classmethod
    def GetRootAs(cls, buf, offset=0):
        n = flatbuffers.encode.Get(flatbuffers.packer.uoffset, buf, offset)
        x = HealthStatusMessage()
        x.Init(buf, n + offset)
        return x

    @classmethod
    def GetRootAsHealthStatusMessage(cls, buf, offset=0):
        """This method is deprecated. Please switch to GetRootAs."""
        return cls.GetRootAs(buf, offset)
    # HealthStatusMessage
    def Init(self, buf, pos):
        self._tab = flatbuffers.table.Table(buf, pos)

    # HealthStatusMessage
    def Dispenser(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(4))
        if o != 0:
            return self._tab.Get(flatbuffers.number_types.Int8Flags, o + self._tab.Pos)
        return 0

    # HealthStatusMessage
    def Icemaker(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(6))
        if o != 0:
            return self._tab.Get(flatbuffers.number_types.Uint32Flags, o + self._tab.Pos)
        return 0

    # HealthStatusMessage
    def Lightbulb(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(8))
        if o != 0:
            return self._tab.Get(flatbuffers.number_types.Int8Flags, o + self._tab.Pos)
        return 0

    # HealthStatusMessage
    def FridgeTemp(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(10))
        if o != 0:
            return self._tab.Get(flatbuffers.number_types.Uint32Flags, o + self._tab.Pos)
        return 0

    # HealthStatusMessage
    def FreezerTemp(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(12))
        if o != 0:
            return self._tab.Get(flatbuffers.number_types.Uint32Flags, o + self._tab.Pos)
        return 0

    # HealthStatusMessage
    def SensorStatus(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(14))
        if o != 0:
            return self._tab.Get(flatbuffers.number_types.Int8Flags, o + self._tab.Pos)
        return 0

def HealthStatusMessageStart(builder): builder.StartObject(6)
def Start(builder):
    return HealthStatusMessageStart(builder)
def HealthStatusMessageAddDispenser(builder, dispenser): builder.PrependInt8Slot(0, dispenser, 0)
def AddDispenser(builder, dispenser):
    return HealthStatusMessageAddDispenser(builder, dispenser)
def HealthStatusMessageAddIcemaker(builder, icemaker): builder.PrependUint32Slot(1, icemaker, 0)
def AddIcemaker(builder, icemaker):
    return HealthStatusMessageAddIcemaker(builder, icemaker)
def HealthStatusMessageAddLightbulb(builder, lightbulb): builder.PrependInt8Slot(2, lightbulb, 0)
def AddLightbulb(builder, lightbulb):
    return HealthStatusMessageAddLightbulb(builder, lightbulb)
def HealthStatusMessageAddFridgeTemp(builder, fridgeTemp): builder.PrependUint32Slot(3, fridgeTemp, 0)
def AddFridgeTemp(builder, fridgeTemp):
    return HealthStatusMessageAddFridgeTemp(builder, fridgeTemp)
def HealthStatusMessageAddFreezerTemp(builder, freezerTemp): builder.PrependUint32Slot(4, freezerTemp, 0)
def AddFreezerTemp(builder, freezerTemp):
    return HealthStatusMessageAddFreezerTemp(builder, freezerTemp)
def HealthStatusMessageAddSensorStatus(builder, sensorStatus): builder.PrependInt8Slot(5, sensorStatus, 0)
def AddSensorStatus(builder, sensorStatus):
    return HealthStatusMessageAddSensorStatus(builder, sensorStatus)
def HealthStatusMessageEnd(builder): return builder.EndObject()
def End(builder):
    return HealthStatusMessageEnd(builder)